### ISSUE TITLE
tencentcloud dependency seems to be gone

### ISSUE THREAD

**Issue by fagossa** [hashicorp/go-discover#172]
Hello people,

I've just realized that this project depends on an unexpected version of `tencentcloud`: https://github.com/hashicorp/go-discover/blob/master/go.mod#L33 :
```
github.com/tencentcloud/tencentcloud-sdk-go v3.0.83+incompatible
```

The tag `v3.0.83` in their repo seems to be [gone](https://github.com/TencentCloud/tencentcloud-sdk-go/tags). I can **still** build locally because I imagine `https://proxy.golang.org` still has the cached version.  However, it won't build using a configuration like this:

```
GOPROXY="direct"
```

So, I was wondering if you have plans for a new version of `go-discover` using an existing tag for `tencentcloud`? 
In `go-discover` currently there are no tags (I know you are aware) so, a default `v0.0.0` version is used in repos dependent on this one (eg, https://github.com/hashicorp/vault/blob/master/go.mod#L63 )

```
github.com/hashicorp/go-discover v0.0.0-20201029210230-738cb3105cd0
```

Edit:
[go-kms-wrapping](https://github.com/hashicorp/go-kms-wrapping/issues/31) seems to have the same problem. I also created an issue over there.

Thanks a lot

**Comment by jeffwidman** [comment]
Hitting the same problem, this is causing Dependabot runs to fail against multiple repo's due to the broken dep tree.

**Comment by jeffwidman** [comment]
I opened #173 to fix this.

**Comment by ncode** [comment]
Hello,

I'm not able to build the conteinerd nomad driver also due to the dependency issue:

/usr/bin/go build -o containerd-driver .
go: github.com/hashicorp/nomad@v1.1.0 requires
        github.com/hashicorp/go-discover@v0.0.0-20200812215701-c4b85f6ed31f requires
        github.com/tencentcloud/tencentcloud-sdk-go@v3.0.83+incompatible: reading github.com/tencentcloud/tencentcloud-sdk-go/go.mod at revision v3.0.83: unknown revision v3.0.83

**Comment by Skjold** [comment]
Tencent had warned about this:

> 注意：为了支持 go mod，SDK 版本号从 v3.x 降到了 v1.x。并于2021.05.10移除了所有v3.0.*和3.0.*的tag，如需追溯以前的tag，请参考项目根目录下的 commit2tag 文件。

Rough translation:

> Note: In order to support go mod, the SDK version number has been reduced from v3.x to v1.x. All tags of v3.0.* and 3.0.* were removed on 2021.05.10. If you need to trace the previous tags, please refer to the commit2tag file in the project root directory.

Please change the tags accordingly ASAP since this breaks the builds of Terraform and Levant among others as well.
