### ISSUE TITLE
Request: Better installation instructions

### ISSUE THREAD

**Issue by flyinbutrs** [hashicorp/go-discover#19]
I can't seem to install this, no doubt because I don't understand how to use Go. But since Hashicorp is recommending it in their vault / consul docs, and it seems like a good tool, I'd like to use it.

I'm on ubuntu, I've done this:

```
sudo apt-get update
sudo apt-get install golang
sudo go get -u github.com/hashicorp/go-discover/cmd/discover
```

First, I got an error about not having a gopath setup, then I tried this:

```
sudo mkdir -p /opt/go-discover
sudo GOPATH=/opt/go-discover go get -u github.com/hashicorp/go-discover/cmd/discover
```

Which outputs:

```
package github.com/hashicorp/go-discover/cmd/discover
	imports context: unrecognized import path "context"
```

And then I still don't have an executable discover. I'm sure this is something silly that would be plainly obvious if I were a go dev, but as someone who just wants to use the tool, I have no idea where to even go from here.

Thanks!

**Comment by slackpad** [comment]
Hi @flyinbutrs this library requires Go 1.7 or later - it looks like that's an error from an older version of Go. This library is built into Consul already, though, so most users don't need to build this directly unless they are integrating it into something else. In Consul, for example, you configure go-discover using the the https://www.consul.io/docs/agent/options.html#retry-join configuration.

**Comment by flyinbutrs** [comment]
Oh, I totally misread that doc, and thought I had to install it separately. Thanks!
