### ISSUE TITLE
azure.PublicCloud.OAuthConfigForTenant undefined (type azure.Environment has no field or method OAuthConfigForTenant)

### ISSUE THREAD

**Issue by nim-nim** [hashicorp/go-discover#24]
Hi,

Witht the latest releases of:
github.com/dgrijalva/jwt-go (3.1.0)
github.com/Azure/go-autorest (9.7.0)
github.com/Azure/azure-sdk-for-go (12.1.1)

# github.com/hashicorp/go-discover/provider/azure
provider/azure/azure_discover.go:49:39: azure.PublicCloud.OAuthConfigForTenant undefined (type azure.Environment has no field or method OAuthConfigForTenant)
provider/azure/azure_discover.go:55:14: undefined: azure.NewServicePrincipalToken
FAIL    github.com/hashicorp/go-discover [build failed]

**Comment by flyinprogrammer** [comment]
yeah i just discovered this (terrible pun, i'm sorry, not sorry)
software is terrible, let's fix this :+1:

**Comment by flyinprogrammer** [comment]
https://github.com/Azure/azure-sdk-for-go/pull/600

seems to be a thing

**Comment by pearkes** [comment]
Fixed in #37!
