### ISSUE TITLE
[Scaleway] discover is not working in PAR1 without public network

### ISSUE THREAD

**Issue by Nainterceptor** [hashicorp/go-discover#45]
Hello !

I'm trying to build this kind of cluster : 

```
     +------------------+Scaleway PAR1+-----+
     |                                      |
     |                                      |
     |                                      |
     |                                      |
     |        +--------------+              |
     |        |   Consul 1   |              |
     |        +--------------+              |
     |                                      |
+----+------+           +----------------+  |
| Jump host |           |    Consul 2    |  |
+----+------+           +----------------+  |
     |                                      |
     |         +-------------+              |
     |         |   Consul 3  |              |
     |         +-------------+              |
     |                                      |
     |                                      |
     |                                      |
     |                                      |
     +--------------------------------------+

```

Here, when Consul server is trying to execute retry_join, I've this kind of message in monitor : 

```
agent: Join LAN: discover-scaleway: Head https://cp-ams1.scaleway.com/servers?: dial tcp 51.15.33.64:443: i/o timeout
2018/06/09 15:33:12 [WARN] agent: Join LAN failed: No servers to join, retrying in 30s
```

That's true, 51.x seems to be a public IP that are not available because as you can see in my quick schema, only Jump Host can access to public.

I don't know why discover is trying to query ams1 server ?

Simple ping seems to be enough to troubleshot  : 
```
root@packer-consul-start1s-2018-06-09-14-47-09:~# ping cp-ams1.scaleway.com
PING cp-ams1.scaleway.com (51.15.33.64) 56(84) bytes of data.
^C



root@packer-consul-start1s-2018-06-09-14-47-09:~# ping cp-par1.scaleway.com
PING cp-par1.scaleway.com (212.47.225.64) 56(84) bytes of data.
64 bytes from 64-225-47-212.int.cloud.online.net (212.47.225.64): icmp_seq=1 ttl=59 time=0.498 ms
64 bytes from 64-225-47-212.int.cloud.online.net (212.47.225.64): icmp_seq=2 ttl=59 time=0.579 ms
^C


root@packer-consul-start1s-2018-06-09-14-47-09:~# ping api.scaleway.com
PING api.scaleway.com (212.47.225.64) 56(84) bytes of data.
64 bytes from 64-225-47-212.int.cloud.online.net (212.47.225.64): icmp_seq=1 ttl=59 time=0.480 ms
64 bytes from 64-225-47-212.int.cloud.online.net (212.47.225.64): icmp_seq=2 ttl=59 time=0.664 ms
^C
```

I think the best may be to use api.scaleway.com, which should be available in all datacenters.

I've tried to look into sources of go-discover. I think we just have to edit this line https://github.com/nicolai86/scaleway-sdk/blob/master/server.go#L196 to use api.scaleway.com (seems to be the same IP than cp.par1.scaleway.com)

I'm OK to test some fixes, but in this case I'll need your help, my last Go code was wrote in 2015... + How to build consul with the fixed discover inside ?

+ ping @nicolai86

Thanks for your help !

**Comment by nicolai86** [comment]
I'm sorry for the inconvenience!

@Nainterceptor can you document the steps taken to trigger the issue? I'd like to try it out myself. Ideally a terraform file and a list of steps you took.

**Comment by Nainterceptor** [comment]
I'm working on something between https://github.com/hashicorp/terraform-aws-consul/ and your demo in https://github.com/nicolai86/scaleway-terraform-demo. So, you should be able to understood it easily I think :)

Thanks for your job by the way !

To debug easier, I've added a repo here with my current work, but I've not added docs, because it's not fully working now :/

* Please create ssh key pair (id_rsa and id_rsa.pub) in .ssh directory (in the cloned folder), and add .pub in scaleway backend. Or edit terraform scripts to remove lines where your find `${file(".ssh/id_rsa")}`.

* Please create consul image thanks to packer. (something like `SCW_ORGANIZATION=... SCW_TOKEN=... packer build -only=scaleway_PAR1_START1S images/consul/consul.json`)

* Please run terraform main script, I'm waiting for scaleway_organization and scaleway_token vars too


Happy debugging !
Once time again, I'm ok to help you, if you have some docs about how to build in packer image directly, to be able to create instances and test it... Seems to be not so simple :D

**Comment by Nainterceptor** [comment]
Everything is working well if each instance has an access to public network. Any news @nicolai86 ?

**Comment by nicolai86** [comment]
@Nainterceptor  looking into this now - might take me a couple of days since I've never worked with go-discover. I'll let you know once I've found a way to resolve this...

**Comment by nicolai86** [comment]
@Nainterceptor I'm pretty certain that #49 will resolve this issue, as the root cause of the error is the fact that sdk used to ignore the computeAPI set inside the client.

I've fixed this issue & am waiting on a review by the maintainers...

**Comment by nicolai86** [comment]
I've pinged the hashicorp people, hope to expedite this somehow to make up for the long wait...
