### ISSUE TITLE
Azure provider returns an undocumented error

### ISSUE THREAD

**Issue by jasonwalsh** [hashicorp/go-discover#51]
I'm trying to use `go-discover` as part of the [cloud-auto-joining](https://www.consul.io/docs/agent/cloud-auto-join.html) feature for Consul. After not being able to configure the `retry_join` parameter in the agent configuration successfully, I decided to use the `discover` binary as documented [here](https://github.com/hashicorp/go-discover#command-line-tool-usage).

What's strange is that every time I try to run the command, it doesn't seem to like the `secret_access_key` parameter, and returns `discover: secret_access_key:` as shown in the screenshot below:

<img width="682" alt="screen shot 2018-07-12 at 1 22 19 pm" src="https://user-images.githubusercontent.com/2184329/42649359-7f4491cc-85d7-11e8-8fed-efacd8218ab5.png">

Am I missing something here? I currently have an Azure virtual machine scale set created in the `guided-swine` resource group. The name of the VMSS is `consul`.

I'm not sure if this is useful, but here's some additional information from `go env`:

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jasonwalsh/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jasonwalsh/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ph/0kqwdgqd5jj9flj8qjw9732c0000gn/T/go-build406674888=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

Any help would be much appreciated. In the meantime, I'll check out the source code to see if I can identify the issue.

Thanks.

**Comment by flyinprogrammer** [comment]
it looks like things are real broken from https://github.com/hashicorp/go-discover/issues/46
let me see what we can do 😞

**Comment by jasonwalsh** [comment]
@flyinprogrammer I can also take a look

**Comment by alvin-huang** [comment]
Hi @jasonwalsh! I know it has been quite some time but can yo utest it with the latest master to see if you are running into the same issue? I don't believe there have been any commits with the Azure discover bits since then but it is working for me from the latest commit. This spins up the Terraform VMSS in https://github.com/hashicorp/go-discover/tree/master/test/tf/azure-vmss and runs the `discover addrs` command on it:

```
bash-3.2$ discover addrs provider=azure client_id=$ARM_CLIENT_ID secret_access_key=$ARM_CLIENT_SECRET tenant_id=$ARM_TENANT_ID subscription_id=$ARM_SUBSCRIPTION_ID resource_group=go-discover-azure-vmss-dev vm_scale_set=go-discover-azure-vmss-01-scale-set
Registered providers: [aliyun aws azure digitalocean gce os packet scaleway softlayer triton vsphere]
[DEBUG] discover: Using provider "azure"
[DEBUG] discover-azure: using vm scale set method. resource_group: go-discover-azure-vmss-dev, vm_scale_set: go-discover-azure-vmss-01-scale-set
Sending GET https://management.azure.com/subscriptions/c0a607b2-6372-4ef3-abdb-dbe52a7b56ba/resourceGroups/go-discover-azure-vmss-dev/providers/microsoft.Compute/virtualMachineScaleSets/go-discover-azure-vmss-01-scale-set/networkInterfaces?api-version=2015-06-15
GET https://management.azure.com/subscriptions/c0a607b2-6372-4ef3-abdb-dbe52a7b56ba/resourceGroups/go-discover-azure-vmss-dev/providers/microsoft.Compute/virtualMachineScaleSets/go-discover-azure-vmss-01-scale-set/networkInterfaces?api-version=2015-06-15 received 200 OK
[DEBUG] discover-azure: Interface /subscriptions/c0a607b2-6372-4ef3-abdb-dbe52a7b56ba/resourceGroups/go-discover-azure-vmss-dev/providers/Microsoft.Compute/virtualMachineScaleSets/go-discover-azure-vmss-01-scale-set/virtualMachines/1/networkInterfaces/go-discover-azure-vmss-01-np has private ip: 10.0.1.5
[DEBUG] discover-azure: Interface /subscriptions/c0a607b2-6372-4ef3-abdb-dbe52a7b56ba/resourceGroups/go-discover-azure-vmss-dev/providers/Microsoft.Compute/virtualMachineScaleSets/go-discover-azure-vmss-01-scale-set/virtualMachines/3/networkInterfaces/go-discover-azure-vmss-01-np has private ip: 10.0.1.7
[DEBUG] discover-azure: Interface /subscriptions/c0a607b2-6372-4ef3-abdb-dbe52a7b56ba/resourceGroups/go-discover-azure-vmss-dev/providers/Microsoft.Compute/virtualMachineScaleSets/go-discover-azure-vmss-01-scale-set/virtualMachines/4/networkInterfaces/go-discover-azure-vmss-01-np has private ip: 10.0.1.8
[DEBUG] discover-azure: Found ip addresses: [10.0.1.5 10.0.1.7 10.0.1.8]
```

**Comment by jasonwalsh** [comment]
Unfortunately I don't have an Azure account anymore, so I'm unable to confirm @alvin-huang.

**Comment by petems** [comment]
So, I encountered a similar error, and the issue was actually a funny one: service principle accounts generated from the CLI create secrets without `=` equals signs in them (presumably to avoid weird terminal interpolation issues). 

However, service principles created from the Azure portal always end in an equals sign! 

If in your configuration, you're not surrounding the value in `'` single quotes, it fails to get the value, leading to the error you see: `discover: secret_access_key:` followed by no returned values. 

This was done on Consul 1.4.2. Ultimately I think it would be good if the logs from the retry_join would return a 403 if the config was incorrect, which would bubble up this error earlier 😄

**Comment by petems** [comment]
My Terraform repo for this is here: https://github.com/petems/terraform-azurerm-vaultstack

The cloud-init code looks like this:

```
sudo tee /etc/consul.d/config.json > /dev/null <<EOF
{
  "acl_datacenter": "dc1",
  "acl_master_token": "${consul_master_token}",
  "acl_token": "${consul_master_token}",
  "acl_default_policy": "allow",
  "advertise_addr": "${private_ip}",
  "advertise_addr_wan": "${public_ip}",
  "bootstrap_expect": ${consul_servers},
  "bind_addr": "$(private_ip)",
  "node_name": "${node_name}",
  "data_dir": "/mnt/consul",
  "disable_update_check": true,
  "encrypt": "${consul_gossip_key}",
  "leave_on_terminate": true,
  "raft_protocol": 3,
  "retry_join": ["provider=azure tag_name=${consul_join_tag_name}  tag_value='${consul_join_tag_value}' tenant_id='${tenant_id}' client_id='${client_id}' subscription_id='${subscription_id}' secret_access_key='${client_secret}' "],

  "server": true,
  "addresses": {
    "http": "0.0.0.0",
    "https": "$(private_ip)"
  },
  "ports": {
    "http": 8500,
    "https": 8533
  },
  "key_file": "/etc/ssl/certs/me.key",
  "cert_file": "/etc/ssl/certs/me.crt",
  "ca_file": "/usr/local/share/ca-certificates/01-me.crt",
  "verify_incoming": false,
  "verify_outgoing": false,
  "verify_server_hostname": false,
  "ui": true
}
EOF
```

**Comment by petems** [comment]
Yep, I've an easily reproducible testcase, it's an equals in the secret block causing the error:

```
./discover addrs provider=azure tag_name=foo tag_value=bar tenant_id=a client_id=b subscription_id=c secret_access_key=foo=bar
Registered providers: [aliyun aws azure digitalocean gce os packet scaleway softlayer triton vsphere]
discover: secret_access_key:
```
