### ISSUE TITLE
go build error

### ISSUE THREAD

**Issue by chinaboard** [hashicorp/go-discover#68]
go: verifying k8s.io/client-go@v8.0.0+incompatible: checksum mismatch
	downloaded: h1:tTI4hRmb1DRMl4fG6Vclfdi6nTM82oIrTT7HfitmxC4=
	go.sum:     h1:7Zl+OVXn0bobcsi4NEZGdoQDTE9ij1zPMfM21+yqQsM=

**Comment by alvin-huang** [comment]
@chinaboard, what go version are you using? I am unable to reproduce this on `go version go1.11 darwin/amd64`

**Comment by chinaboard** [comment]
@alvin-huang 
go version go1.11.2 darwin/amd64

and you can see other pr travis build details

**Comment by pearkes** [comment]
Ah yeah here is an example: https://travis-ci.org/hashicorp/go-discover/builds/466369612?utm_source=github_status&utm_medium=notification

**Comment by u007** [comment]
any workaround?
i found another issue, not sure if this is related:
```
go: verifying github.com/hashicorp/go-rootcerts@v0.0.0-20160503143440-6bb64b370b90: checksum mismatch
	downloaded: h1:VBj0QYQ0u2MCJzBfeYXGexnAl17GsH1yidnoxCqqD9E=
	go.sum:     h1:9HVkPxOpo+yO93Ah4yrO67d/qh0fbLLWbKqhYjyHq9A=
```

**Comment by szank** [comment]
I got exactly the same error as above. At least I am not insane.

**Comment by u007** [comment]
ive the fix, if u r using docker, use golang:1.11.1

**Comment by blalor** [comment]
I've verified that this problem only exists (on macOS 10.14.2) with go 1.11.4.

**Comment by blalor** [comment]
This may be related to https://github.com/golang/go/issues/29278#issuecomment-447571410; @u007 with golang 1.11.4, could you try deleting `go.sum`, running `go clean -modcache`, and then seeing if your problem disappears?

**Comment by u007** [comment]
i tried that, didnt work.
it also happen in my ci deployment via gitlab runner i docker build when i use golang 1.11.4 or higher

**Comment by u007** [comment]
just realise, i need to 1st go clean -modcache, then only delete go.sum, then go get , then it works

**Comment by u007** [comment]
on my mac it works, but on docker golang:1.11, it does not even with latest go.sum updated

**Comment by blalor** [comment]
In my testing I found that for affected dependencies, a `go.sum` generated on 1.11.3 will generate the checksum error in 1.11.4, and vice versa.

**Comment by lidalei** [comment]
Specifying `github.com/hashicorp/go-rootcerts v1.0.0` in go.mod solves my problem in MacOS.

**Comment by u007** [comment]
nice, this is new :)
